global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'propertyservice-monitor'
    environment: '${ENVIRONMENT:-local}'

scrape_configs:
  - job_name: 'propertyservice-api'
    static_configs:
      - targets: ['${API_HOST:-api}:${API_PORT:-8080}']
        labels:
          application: 'propertyservice-api'
          environment: '${ENVIRONMENT:-local}'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
