kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: agro-dev

nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080
      - containerPort: 30081
        hostPort: 30081
      - containerPort: 30082
        hostPort: 30082
      - containerPort: 30032
        hostPort: 30032
      - containerPort: 30033
        hostPort: 30033
      - containerPort: 5000
        hostPort: 5000
      - containerPort: 30380
        hostPort: 30380
      - containerPort: 30980
        hostPort: 30980
      - containerPort: 30381
        hostPort: 30381
      - containerPort: 30981
        hostPort: 30981
      - containerPort: 30300
        hostPort: 30300
      - containerPort: 30900
        hostPort: 30900
      - containerPort: 30000
        hostPort: 30000
      - containerPort: 30902
        hostPort: 30902
      - containerPort: 5672
        hostPort: 5672
      - containerPort: 15672
        hostPort: 15672
  - role: worker
