kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dev-propertyservice

nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080
      - containerPort: 30032
        hostPort: 30032

  - role: worker
